# Session 2: Exploring Indian social and demographic data with Pandas

**Dataset:** RBI Handbook of Statistics on Indian States  
**Goal:** Learn how to inspect, filter, sort and summarise a real dataset using Pandas.

By the end of this notebook, you should be able to:

- load an Excel file into Pandas
- understand what one row and one column represent
- inspect a dataframe
- select columns
- filter rows
- sort values
- calculate simple summaries
- identify missing values
- write down possible reporting leads

## Before we begin: Colab, Jupyter Notebook and VS Code

### Google Colab
- Runs in a browser
- Requires no installation
- Useful for classes, quick analysis and sharing notebooks

### Jupyter Notebook
- Runs on your own computer
- Uses the same notebook-style workflow as Colab
- Useful for exploratory data analysis

### VS Code
- A full code editor
- Better for larger projects with many files
- Useful when you move beyond a single notebook

> **For this class, we will continue using Google Colab.**

## 1. Import Pandas

In [75]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\Abhimanyu Singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Abhimanyu Singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Abhimanyu Singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Abhimanyu Singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Abhimanyu Singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [76]:
import pandas as pd

## 2. Upload the Excel file from your computer

Run the cell below and choose the combined RBI Excel file.

In [77]:
pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\Abhimanyu Singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\Abhimanyu Singh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [78]:
df = pd.read_excel('india_social_demographic_indicators_combined.xlsx')

In [79]:
df.columns = df.columns.str.replace(" ", "_")
df.columns = df.columns.str.replace("-", "_")
df.columns = df.columns.str.lower()
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:,.2f}'.format

## 3. Read the `data sheet`

`pd.read_excel()` reads an Excel sheet and stores it as a Pandas dataframe.
\
`pd.read_csv()` reads csvs and stores them as Pandas dataframe.

In [80]:
df.shape

(37, 13)

In [81]:
df.head(37)

,state,gross_enrolment_ratio_secondary_total,birth_rate_per_1000,death_rate_per_1000,infant_mortality_rate_per_1000,maternal_mortality_ratio_per_100000_live_births,total_fertility_rate,life_expectancy_years_total,rural_unemployment_rate_per_1000,urban_unemployment_rate_per_1000,multidimensional_poverty_headcount_percent,natural_population_growth_rate,gender_parity_index_secondary
0,Andaman and Nicobar Islands,89.10,10.10,6.30,9.00,NaN,NaN,NaN,106,135,2.30,3.80,1.20
1,Andhra Pradesh,78.50,15.00,6.90,19.00,30.00,1.50,70.70,34,59,6.06,8.10,1.00
2,Arunachal Pradesh,56.70,16.60,5.50,20.00,NaN,NaN,NaN,50,128,13.76,11.10,1.10
3,Assam,61.50,19.80,6.20,30.00,110.00,2.00,68.60,35,74,19.35,13.60,1.20
4,Bihar,44.70,25.80,6.10,23.00,104.00,2.80,69.30,26,73,33.76,19.70,1.10
5,Chandigarh,108.70,11.10,4.00,7.00,NaN,NaN,NaN,32,71,3.52,7.10,1.20
6,Chhattisgarh,65.60,22.30,8.30,37.00,146.00,2.20,64.60,15,76,16.37,14.00,1.20
7,Dadra & Nagar Haveli,NaN,21.90,3.70,11.00,NaN,NaN,NaN,10,50,NaN,18.20,NaN
8,Daman & Diu,NaN,18.60,4.10,17.00,NaN,NaN,NaN,32,28,NaN,14.50,NaN
9,Delhi,91.70,12.90,4.50,14.00,NaN,1.20,74.20,60,20,3.43,8.40,1.10
10,Goa,100.80,10.80,6.80,6.00,NaN,NaN,NaN,89,82,0.84,3.90,1.10
11,Gujarat,61.00,17.60,6.40,20.00,51.00,1.80,70.40,4,23,11.66,11.20,1.00
12,Haryana,81.00,18.70,6.80,26.00,89.00,1.90,68.80,31,40,7.07,11.90,1.00
13,Himachal Pradesh,93.60,14.30,6.70,14.00,NaN,1.60,74.40,50,90,4.93,7.60,1.10
14,Jammu and Kashmir,55.20,14.80,5.60,14.00,NaN,1.50,74.40,50,114,4.80,10.50,1.10
15,Jharkhand,60.60,20.60,6.30,29.00,54.00,2.10,69.50,5,58,28.81,14.30,1.10
16,Karnataka,81.30,15.20,6.80,14.00,68.00,1.50,70.00,19,42,7.58,8.30,1.10
17,Kerala,94.10,12.30,7.20,5.00,30.00,1.50,75.10,76,67,0.55,5.00,1.00
18,Ladakh,70.40,14.60,5.50,NaN,NaN,NaN,NaN,39,134,3.53,9.10,1.20
19,Lakshadweep,65.30,13.40,5.50,9.00,NaN,NaN,NaN,83,138,1.11,7.90,1.00
20,Madhya Pradesh,56.70,22.50,6.80,37.00,142.00,2.40,67.60,5,28,20.63,15.80,1.00
21,Maharashtra,82.10,14.00,6.10,14.00,36.00,1.40,72.80,22,52,7.81,7.90,1.00
22,Manipur,68.70,13.00,4.50,3.00,NaN,NaN,NaN,55,75,8.10,8.50,1.00
23,Meghalaya,62.50,22.70,5.50,34.00,NaN,NaN,NaN,51,140,27.79,17.30,1.40
24,Mizoram,73.70,14.20,5.90,13.00,NaN,NaN,NaN,13,34,5.30,8.20,1.20
25,Nagaland,50.50,13.60,5.50,10.00,NaN,NaN,NaN,57,113,15.43,8.10,1.20
26,Odisha,72.30,16.00,7.70,30.00,153.00,1.70,70.50,26,68,15.68,8.40,1.10
27,Puducherry,96.90,12.10,6.40,7.00,NaN,NaN,NaN,19,65,0.85,5.70,1.10
28,Punjab,86.00,13.80,7.30,17.00,90.00,1.50,70.80,54,56,4.75,6.40,1.10
29,Rajasthan,74.20,22.90,5.90,29.00,86.00,2.30,70.40,32,77,15.31,16.90,1.00
30,Sikkim,60.20,14.70,4.80,6.00,NaN,NaN,NaN,22,30,2.60,9.90,1.10
31,Tamil Nadu,89.40,12.00,6.90,12.00,35.00,1.30,73.40,31,41,2.20,5.00,1.10
32,Telangana,83.60,15.80,6.30,18.00,59.00,1.50,70.80,35,73,5.88,9.50,1.10
33,Tripura,67.70,15.30,6.20,15.00,NaN,NaN,NaN,14,32,13.11,9.10,1.10
34,Uttar Pradesh,60.90,23.60,6.50,37.00,141.00,2.60,68.00,22,67,22.93,17.10,1.00
35,Uttarakhand,87.10,16.90,6.10,20.00,91.00,1.70,71.30,39,58,9.67,10.70,1.10
36,West Bengal,75.20,14.00,5.70,17.00,104.00,1.30,72.50,23,33,11.89,8.30,1.20

In [82]:
df.tail()

,state,gross_enrolment_ratio_secondary_total,birth_rate_per_1000,death_rate_per_1000,infant_mortality_rate_per_1000,maternal_mortality_ratio_per_100000_live_births,total_fertility_rate,life_expectancy_years_total,rural_unemployment_rate_per_1000,urban_unemployment_rate_per_1000,multidimensional_poverty_headcount_percent,natural_population_growth_rate,gender_parity_index_secondary
32,Telangana,83.60,15.80,6.30,18.00,59.00,1.50,70.80,35,73,5.88,9.50,1.10
33,Tripura,67.70,15.30,6.20,15.00,NaN,NaN,NaN,14,32,13.11,9.10,1.10
34,Uttar Pradesh,60.90,23.60,6.50,37.00,141.00,2.60,68.00,22,67,22.93,17.10,1.00
35,Uttarakhand,87.10,16.90,6.10,20.00,91.00,1.70,71.30,39,58,9.67,10.70,1.10
36,West Bengal,75.20,14.00,5.70,17.00,104.00,1.30,72.50,23,33,11.89,8.30,1.20

### Pause before coding

1. What does one row represent?
2. What does one column represent?
3. Which columns contain text?
4. Which columns contain numbers?
5. Which variables might be related?

### INSERT OBSERVATIONS HERE

## 4. Inspect the dataframe

In [83]:
df.tail(10)

,state,gross_enrolment_ratio_secondary_total,birth_rate_per_1000,death_rate_per_1000,infant_mortality_rate_per_1000,maternal_mortality_ratio_per_100000_live_births,total_fertility_rate,life_expectancy_years_total,rural_unemployment_rate_per_1000,urban_unemployment_rate_per_1000,multidimensional_poverty_headcount_percent,natural_population_growth_rate,gender_parity_index_secondary
27,Puducherry,96.90,12.10,6.40,7.00,NaN,NaN,NaN,19,65,0.85,5.70,1.10
28,Punjab,86.00,13.80,7.30,17.00,90.00,1.50,70.80,54,56,4.75,6.40,1.10
29,Rajasthan,74.20,22.90,5.90,29.00,86.00,2.30,70.40,32,77,15.31,16.90,1.00
30,Sikkim,60.20,14.70,4.80,6.00,NaN,NaN,NaN,22,30,2.60,9.90,1.10
31,Tamil Nadu,89.40,12.00,6.90,12.00,35.00,1.30,73.40,31,41,2.20,5.00,1.10
32,Telangana,83.60,15.80,6.30,18.00,59.00,1.50,70.80,35,73,5.88,9.50,1.10
33,Tripura,67.70,15.30,6.20,15.00,NaN,NaN,NaN,14,32,13.11,9.10,1.10
34,Uttar Pradesh,60.90,23.60,6.50,37.00,141.00,2.60,68.00,22,67,22.93,17.10,1.00
35,Uttarakhand,87.10,16.90,6.10,20.00,91.00,1.70,71.30,39,58,9.67,10.70,1.10
36,West Bengal,75.20,14.00,5.70,17.00,104.00,1.30,72.50,23,33,11.89,8.30,1.20

In [84]:
df.shape

(37, 13)

In [85]:
df.columns

Index(['state', 'gross_enrolment_ratio_secondary_total', 'birth_rate_per_1000',
       'death_rate_per_1000', 'infant_mortality_rate_per_1000',
       'maternal_mortality_ratio_per_100000_live_births',
       'total_fertility_rate', 'life_expectancy_years_total',
       'rural_unemployment_rate_per_1000', 'urban_unemployment_rate_per_1000',
       'multidimensional_poverty_headcount_percent',
       'natural_population_growth_rate', 'gender_parity_index_secondary'],
      dtype='str')

In [86]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 13 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   state                                            37 non-null     str
 1   gross_enrolment_ratio_secondary_total            35 non-null     float64
 2   birth_rate_per_1000                              37 non-null     float64
 3   death_rate_per_1000                              37 non-null     float64
 4   infant_mortality_rate_per_1000                   36 non-null     float64
 5   maternal_mortality_ratio_per_100000_live_births  19 non-null     float64
 6   total_fertility_rate                             22 non-null     float64
 7   life_expectancy_years_total                      22 non-null     float64
 8   rural_unemployment_rate_per_1000                 37 non-null     int64
 9   urban_unemployment_rate_per_1000                 37 non-null     int64
 10  multidimensional_poverty_headcount_percent       35 non-null     float64
 11  natural_population_growth_rate                   37 non-null     float64
 12  gender_parity_index_secondary                    35 non-null     float64
dtypes: float64(10), int64(2), str(1)
memory usage: 3.9 KB

In [87]:
df.sort_values(by=['multidimensional_poverty_headcount_percent', 'infant_mortality_rate_per_1000'], ascending=False).head(5)

,state,gross_enrolment_ratio_secondary_total,birth_rate_per_1000,death_rate_per_1000,infant_mortality_rate_per_1000,maternal_mortality_ratio_per_100000_live_births,total_fertility_rate,life_expectancy_years_total,rural_unemployment_rate_per_1000,urban_unemployment_rate_per_1000,multidimensional_poverty_headcount_percent,natural_population_growth_rate,gender_parity_index_secondary
4,Bihar,44.70,25.80,6.10,23.00,104.00,2.80,69.30,26,73,33.76,19.70,1.10
15,Jharkhand,60.60,20.60,6.30,29.00,54.00,2.10,69.50,5,58,28.81,14.30,1.10
23,Meghalaya,62.50,22.70,5.50,34.00,NaN,NaN,NaN,51,140,27.79,17.30,1.40
34,Uttar Pradesh,60.90,23.60,6.50,37.00,141.00,2.60,68.00,22,67,22.93,17.10,1.00
20,Madhya Pradesh,56.70,22.50,6.80,37.00,142.00,2.40,67.60,5,28,20.63,15.80,1.00

In [88]:
df.describe()

,gross_enrolment_ratio_secondary_total,birth_rate_per_1000,death_rate_per_1000,infant_mortality_rate_per_1000,maternal_mortality_ratio_per_100000_live_births,total_fertility_rate,life_expectancy_years_total,rural_unemployment_rate_per_1000,urban_unemployment_rate_per_1000,multidimensional_poverty_headcount_percent,natural_population_growth_rate,gender_parity_index_secondary
count,35.00,37.00,37.00,36.00,19.00,22.00,22.00,37.00,37.00,35.00,37.00,35.00
mean,74.50,16.31,6.04,17.86,85.21,1.79,70.82,36.92,68.76,10.27,10.30,1.10
std,15.52,4.09,1.02,9.74,40.95,0.45,2.58,24.00,34.75,8.67,4.16,0.09
min,44.70,10.10,3.70,3.00,30.00,1.20,64.60,4.00,20.00,0.55,3.80,1.00
25%,61.25,13.60,5.50,10.75,52.50,1.50,69.35,22.00,41.00,3.52,7.90,1.00
50%,73.70,15.00,6.20,16.00,89.00,1.65,70.60,32.00,67.00,7.58,9.10,1.10
75%,86.55,18.70,6.80,23.75,107.00,2.08,72.72,50.00,77.00,15.37,13.60,1.15
max,108.70,25.80,8.30,37.00,153.00,2.80,75.10,106.00,140.00,33.76,19.70,1.40

In [89]:
df.index

RangeIndex(start=0, stop=37, step=1)

### Questions

- How many rows and columns are there?
- Which indicator has the largest range?
- Do any minimum or maximum values look surprising?

## 5. Select columns

In [90]:
df["state"]

0     Andaman and Nicobar Islands
1                  Andhra Pradesh
2               Arunachal Pradesh
3                           Assam
4                           Bihar
5                      Chandigarh
6                    Chhattisgarh
7            Dadra & Nagar Haveli
8                     Daman & Diu
9                           Delhi
10                            Goa
11                        Gujarat
12                        Haryana
13               Himachal Pradesh
14              Jammu and Kashmir
15                      Jharkhand
16                      Karnataka
17                         Kerala
18                         Ladakh
19                    Lakshadweep
20                 Madhya Pradesh
21                    Maharashtra
22                        Manipur
23                      Meghalaya
24                        Mizoram
25                       Nagaland
26                         Odisha
27                     Puducherry
28                         Punjab
29                      Rajasthan
30                         Sikkim
31                     Tamil Nadu
32                      Telangana
33                        Tripura
34                  Uttar Pradesh
35                    Uttarakhand
36                    West Bengal
Name: state, dtype: str

In [91]:
df[[
    "state",
    "infant_mortality_rate_per_1000",
    "life_expectancy_years_total"
]]

,state,infant_mortality_rate_per_1000,life_expectancy_years_total
0,Andaman and Nicobar Islands,9.00,NaN
1,Andhra Pradesh,19.00,70.70
2,Arunachal Pradesh,20.00,NaN
3,Assam,30.00,68.60
4,Bihar,23.00,69.30
5,Chandigarh,7.00,NaN
6,Chhattisgarh,37.00,64.60
7,Dadra & Nagar Haveli,11.00,NaN
8,Daman & Diu,17.00,NaN
9,Delhi,14.00,74.20
10,Goa,6.00,NaN
11,Gujarat,20.00,70.40
12,Haryana,26.00,68.80
13,Himachal Pradesh,14.00,74.40
14,Jammu and Kashmir,14.00,74.40
15,Jharkhand,29.00,69.50
16,Karnataka,14.00,70.00
17,Kerala,5.00,75.10
18,Ladakh,NaN,NaN
19,Lakshadweep,9.00,NaN
20,Madhya Pradesh,37.00,67.60
21,Maharashtra,14.00,72.80
22,Manipur,3.00,NaN
23,Meghalaya,34.00,NaN
24,Mizoram,13.00,NaN
25,Nagaland,10.00,NaN
26,Odisha,30.00,70.50
27,Puducherry,7.00,NaN
28,Punjab,17.00,70.80
29,Rajasthan,29.00,70.40
30,Sikkim,6.00,NaN
31,Tamil Nadu,12.00,73.40
32,Telangana,18.00,70.80
33,Tripura,15.00,NaN
34,Uttar Pradesh,37.00,68.00
35,Uttarakhand,20.00,71.30
36,West Bengal,17.00,72.50

### Try it yourself

Display only:

- `state`
- `birth_rate_per_1000`
- `total_fertility_rate`

In [92]:
df[["state", "birth_rate_per_1000", "total_fertility_rate"]]

                          state  birth_rate_per_1000  total_fertility_rate
0   Andaman and Nicobar Islands                10.10                   NaN
1                Andhra Pradesh                15.00                  1.50
2             Arunachal Pradesh                16.60                   NaN
3                         Assam                19.80                  2.00
4                         Bihar                25.80                  2.80
5                    Chandigarh                11.10                   NaN
6                  Chhattisgarh                22.30                  2.20
7          Dadra & Nagar Haveli                21.90                   NaN
8                   Daman & Diu                18.60                   NaN
9                         Delhi                12.90                  1.20
10                          Goa                10.80                   NaN
11                      Gujarat                17.60                  1.80
12                      Haryana                18.70                  1.90
13             Himachal Pradesh                14.30                  1.60
14            Jammu and Kashmir                14.80                  1.50
15                    Jharkhand                20.60                  2.10
16                    Karnataka                15.20                  1.50
17                       Kerala                12.30                  1.50
18                       Ladakh                14.60                   NaN
19                  Lakshadweep                13.40                   NaN
20               Madhya Pradesh                22.50                  2.40
21                  Maharashtra                14.00                  1.40
22                      Manipur                13.00                   NaN
23                    Meghalaya                22.70                   NaN
24                      Mizoram                14.20                   NaN
25                     Nagaland                13.60                   NaN
26                       Odisha                16.00                  1.70
27                   Puducherry                12.10                   NaN
28                       Punjab                13.80                  1.50
29                    Rajasthan                22.90                  2.30
30                       Sikkim                14.70                   NaN
31                   Tamil Nadu                12.00                  1.30
32                    Telangana                15.80                  1.50
33                      Tripura                15.30                   NaN
34                Uttar Pradesh                23.60                  2.60
35                  Uttarakhand                16.90                  1.70
36                  West Bengal                14.00                  1.30

In [93]:
df[["state", "natural_population_growth_rate"]]

                          state  natural_population_growth_rate
0   Andaman and Nicobar Islands                            3.80
1                Andhra Pradesh                            8.10
2             Arunachal Pradesh                           11.10
3                         Assam                           13.60
4                         Bihar                           19.70
5                    Chandigarh                            7.10
6                  Chhattisgarh                           14.00
7          Dadra & Nagar Haveli                           18.20
8                   Daman & Diu                           14.50
9                         Delhi                            8.40
10                          Goa                            3.90
11                      Gujarat                           11.20
12                      Haryana                           11.90
13             Himachal Pradesh                            7.60
14            Jammu and Kashmir                           10.50
15                    Jharkhand                           14.30
16                    Karnataka                            8.30
17                       Kerala                            5.00
18                       Ladakh                            9.10
19                  Lakshadweep                            7.90
20               Madhya Pradesh                           15.80
21                  Maharashtra                            7.90
22                      Manipur                            8.50
23                    Meghalaya                           17.30
24                      Mizoram                            8.20
25                     Nagaland                            8.10
26                       Odisha                            8.40
27                   Puducherry                            5.70
28                       Punjab                            6.40
29                    Rajasthan                           16.90
30                       Sikkim                            9.90
31                   Tamil Nadu                            5.00
32                    Telangana                            9.50
33                      Tripura                            9.10
34                Uttar Pradesh                           17.10
35                  Uttarakhand                           10.70
36                  West Bengal                            8.30

## 6. Sort values

In [94]:
df.sort_values(
    by="life_expectancy_years_total",
    ascending=False
)[["state", "life_expectancy_years_total"]].head(10)

                state  life_expectancy_years_total
17             Kerala                        75.10
13   Himachal Pradesh                        74.40
14  Jammu and Kashmir                        74.40
9               Delhi                        74.20
31         Tamil Nadu                        73.40
21        Maharashtra                        72.80
36        West Bengal                        72.50
35        Uttarakhand                        71.30
32          Telangana                        70.80
28             Punjab                        70.80

In [95]:
df.sort_values(
    by="natural_population_growth_rate",
    ascending=True
)[["state", "natural_population_growth_rate"]].head(7)

                          state  natural_population_growth_rate
0   Andaman and Nicobar Islands                            3.80
10                          Goa                            3.90
31                   Tamil Nadu                            5.00
17                       Kerala                            5.00
27                   Puducherry                            5.70
28                       Punjab                            6.40
5                    Chandigarh                            7.10

### Try it yourself
Find the ten places with the highest multidimensional poverty headcount.

In [96]:
df.sort_values(
    by="multidimensional_poverty_headcount_percent",
    ascending=False
)[["state", "multidimensional_poverty_headcount_percent"]].head(10)

             state  multidimensional_poverty_headcount_percent
4            Bihar                                       33.76
15       Jharkhand                                       28.81
23       Meghalaya                                       27.79
34   Uttar Pradesh                                       22.93
20  Madhya Pradesh                                       20.63
3            Assam                                       19.35
6     Chhattisgarh                                       16.37
26          Odisha                                       15.68
25        Nagaland                                       15.43
29       Rajasthan                                       15.31

## 7. Filter rows

In [97]:
df[df["state"] == "Rajasthan"]

,state,gross_enrolment_ratio_secondary_total,birth_rate_per_1000,death_rate_per_1000,infant_mortality_rate_per_1000,maternal_mortality_ratio_per_100000_live_births,total_fertility_rate,life_expectancy_years_total,rural_unemployment_rate_per_1000,urban_unemployment_rate_per_1000,multidimensional_poverty_headcount_percent,natural_population_growth_rate,gender_parity_index_secondary
29,Rajasthan,74.20,22.90,5.90,29.00,86.00,2.30,70.40,32,77,15.31,16.90,1.00

In [98]:
df[df["infant_mortality_rate_per_1000"] > 30][[
    "state",
    "infant_mortality_rate_per_1000"
]]

             state  infant_mortality_rate_per_1000
6     Chhattisgarh                           37.00
20  Madhya Pradesh                           37.00
23       Meghalaya                           34.00
34   Uttar Pradesh                           37.00

In [99]:
df[df["life_expectancy_years_total"] < 70][[
    "state",
    "life_expectancy_years_total"
]]

             state  life_expectancy_years_total
3            Assam                        68.60
4            Bihar                        69.30
6     Chhattisgarh                        64.60
12         Haryana                        68.80
15       Jharkhand                        69.50
20  Madhya Pradesh                        67.60
34   Uttar Pradesh                        68.00

In [100]:
df[df["natural_population_growth_rate"] > 10][[
    "state",
    "natural_population_growth_rate"
]]

                   state  natural_population_growth_rate
2      Arunachal Pradesh                           11.10
3                  Assam                           13.60
4                  Bihar                           19.70
6           Chhattisgarh                           14.00
7   Dadra & Nagar Haveli                           18.20
8            Daman & Diu                           14.50
11               Gujarat                           11.20
12               Haryana                           11.90
14     Jammu and Kashmir                           10.50
15             Jharkhand                           14.30
20        Madhya Pradesh                           15.80
23             Meghalaya                           17.30
29             Rajasthan                           16.90
34         Uttar Pradesh                           17.10
35           Uttarakhand                           10.70

### Try it yourself

Find places where:

- total fertility rate is greater than 2
- poverty headcount is greater than 20%

In [101]:
df[
    (df["total_fertility_rate"] > 2) &
    (df["multidimensional_poverty_headcount_percent"] > 20)
][[
    "state",
    "total_fertility_rate",
    "multidimensional_poverty_headcount_percent"
]]

,state,total_fertility_rate,multidimensional_poverty_headcount_percent
4,Bihar,2.80,33.76
15,Jharkhand,2.10,28.81
20,Madhya Pradesh,2.40,20.63
34,Uttar Pradesh,2.60,22.93

## 8. A shorter way to filter

In [102]:
df["total_fertility_rate"]
df["total_fertility_rate"] > 2
df[df["total_fertility_rate"] > 2]

,state,gross_enrolment_ratio_secondary_total,birth_rate_per_1000,death_rate_per_1000,infant_mortality_rate_per_1000,maternal_mortality_ratio_per_100000_live_births,total_fertility_rate,life_expectancy_years_total,rural_unemployment_rate_per_1000,urban_unemployment_rate_per_1000,multidimensional_poverty_headcount_percent,natural_population_growth_rate,gender_parity_index_secondary
4,Bihar,44.70,25.80,6.10,23.00,104.00,2.80,69.30,26,73,33.76,19.70,1.10
6,Chhattisgarh,65.60,22.30,8.30,37.00,146.00,2.20,64.60,15,76,16.37,14.00,1.20
15,Jharkhand,60.60,20.60,6.30,29.00,54.00,2.10,69.50,5,58,28.81,14.30,1.10
20,Madhya Pradesh,56.70,22.50,6.80,37.00,142.00,2.40,67.60,5,28,20.63,15.80,1.00
29,Rajasthan,74.20,22.90,5.90,29.00,86.00,2.30,70.40,32,77,15.31,16.90,1.00
34,Uttar Pradesh,60.90,23.60,6.50,37.00,141.00,2.60,68.00,22,67,22.93,17.10,1.00

In [103]:
df.query("total_fertility_rate > 2")

,state,gross_enrolment_ratio_secondary_total,birth_rate_per_1000,death_rate_per_1000,infant_mortality_rate_per_1000,maternal_mortality_ratio_per_100000_live_births,total_fertility_rate,life_expectancy_years_total,rural_unemployment_rate_per_1000,urban_unemployment_rate_per_1000,multidimensional_poverty_headcount_percent,natural_population_growth_rate,gender_parity_index_secondary
4,Bihar,44.70,25.80,6.10,23.00,104.00,2.80,69.30,26,73,33.76,19.70,1.10
6,Chhattisgarh,65.60,22.30,8.30,37.00,146.00,2.20,64.60,15,76,16.37,14.00,1.20
15,Jharkhand,60.60,20.60,6.30,29.00,54.00,2.10,69.50,5,58,28.81,14.30,1.10
20,Madhya Pradesh,56.70,22.50,6.80,37.00,142.00,2.40,67.60,5,28,20.63,15.80,1.00
29,Rajasthan,74.20,22.90,5.90,29.00,86.00,2.30,70.40,32,77,15.31,16.90,1.00
34,Uttar Pradesh,60.90,23.60,6.50,37.00,141.00,2.60,68.00,22,67,22.93,17.10,1.00

In [104]:
df.query("natural_population_growth_rate > 10")

,state,gross_enrolment_ratio_secondary_total,birth_rate_per_1000,death_rate_per_1000,infant_mortality_rate_per_1000,maternal_mortality_ratio_per_100000_live_births,total_fertility_rate,life_expectancy_years_total,rural_unemployment_rate_per_1000,urban_unemployment_rate_per_1000,multidimensional_poverty_headcount_percent,natural_population_growth_rate,gender_parity_index_secondary
2,Arunachal Pradesh,56.70,16.60,5.50,20.00,NaN,NaN,NaN,50,128,13.76,11.10,1.10
3,Assam,61.50,19.80,6.20,30.00,110.00,2.00,68.60,35,74,19.35,13.60,1.20
4,Bihar,44.70,25.80,6.10,23.00,104.00,2.80,69.30,26,73,33.76,19.70,1.10
6,Chhattisgarh,65.60,22.30,8.30,37.00,146.00,2.20,64.60,15,76,16.37,14.00,1.20
7,Dadra & Nagar Haveli,NaN,21.90,3.70,11.00,NaN,NaN,NaN,10,50,NaN,18.20,NaN
8,Daman & Diu,NaN,18.60,4.10,17.00,NaN,NaN,NaN,32,28,NaN,14.50,NaN
11,Gujarat,61.00,17.60,6.40,20.00,51.00,1.80,70.40,4,23,11.66,11.20,1.00
12,Haryana,81.00,18.70,6.80,26.00,89.00,1.90,68.80,31,40,7.07,11.90,1.00
14,Jammu and Kashmir,55.20,14.80,5.60,14.00,NaN,1.50,74.40,50,114,4.80,10.50,1.10
15,Jharkhand,60.60,20.60,6.30,29.00,54.00,2.10,69.50,5,58,28.81,14.30,1.10
20,Madhya Pradesh,56.70,22.50,6.80,37.00,142.00,2.40,67.60,5,28,20.63,15.80,1.00
23,Meghalaya,62.50,22.70,5.50,34.00,NaN,NaN,NaN,51,140,27.79,17.30,1.40
29,Rajasthan,74.20,22.90,5.90,29.00,86.00,2.30,70.40,32,77,15.31,16.90,1.00
34,Uttar Pradesh,60.90,23.60,6.50,37.00,141.00,2.60,68.00,22,67,22.93,17.10,1.00
35,Uttarakhand,87.10,16.90,6.10,20.00,91.00,1.70,71.30,39,58,9.67,10.70,1.10

## 9. Calculate simple summaries

In [105]:
df["infant_mortality_rate_per_1000"].mean()

np.float64(17.86111111111111)

In [106]:
df["infant_mortality_rate_per_1000"].mean().round(2)

np.float64(17.86)

In [107]:
df["infant_mortality_rate_per_1000"].median()

np.float64(16.0)

In [108]:
df["life_expectancy_years_total"].min()

np.float64(64.6)

In [109]:
df["life_expectancy_years_total"].max()

np.float64(75.1)

In [110]:
df.life_expectancy_years_total.max()

np.float64(75.1)

In [111]:
df["natural_population_growth_rate"].mean()

np.float64(10.297297297297298)

In [112]:
df["natural_population_growth_rate"].mean().round(2)

np.float64(10.3)

In [113]:
df["natural_population_growth_rate"].median()

np.float64(9.1)

In [114]:
df["natural_population_growth_rate"].min()

np.float64(3.8)

In [115]:
df["natural_population_growth_rate"].max()

np.float64(19.7)

In [116]:
df.natural_population_growth_rate.mean().round(1)

np.float64(10.3)

## 10. Check missing values

A missing value does not necessarily mean an error. It may mean an indicator was not published for that state or period.

In [117]:
df.isna().sum().sort_values(ascending=False)

maternal_mortality_ratio_per_100000_live_births    18
total_fertility_rate                               15
life_expectancy_years_total                        15
multidimensional_poverty_headcount_percent          2
gross_enrolment_ratio_secondary_total               2
gender_parity_index_secondary                       2
infant_mortality_rate_per_1000                      1
state                                               0
birth_rate_per_1000                                 0
death_rate_per_1000                                 0
rural_unemployment_rate_per_1000                    0
urban_unemployment_rate_per_1000                    0
natural_population_growth_rate                      0
dtype: int64

In [118]:
df[df["life_expectancy_years_total"].isna()][[
    "state",
    "life_expectancy_years_total"
]]

                          state  life_expectancy_years_total
0   Andaman and Nicobar Islands                          NaN
2             Arunachal Pradesh                          NaN
5                    Chandigarh                          NaN
7          Dadra & Nagar Haveli                          NaN
8                   Daman & Diu                          NaN
10                          Goa                          NaN
18                       Ladakh                          NaN
19                  Lakshadweep                          NaN
22                      Manipur                          NaN
23                    Meghalaya                          NaN
24                      Mizoram                          NaN
25                     Nagaland                          NaN
27                   Puducherry                          NaN
30                       Sikkim                          NaN
33                      Tripura                          NaN

In [119]:
df[df["infant_mortality_rate_per_1000"].isna()][[
    "state",
    "infant_mortality_rate_per_1000"
]]

     state  infant_mortality_rate_per_1000
18  Ladakh                             NaN

## 11. Compare two variables

For now, we are looking for patterns, not claiming causation.

In [120]:
df[[
    "state",
    "multidimensional_poverty_headcount_percent",
    "infant_mortality_rate_per_1000"
]].sort_values(
    "multidimensional_poverty_headcount_percent",
    ascending=False
).head(10)

,state,multidimensional_poverty_headcount_percent,infant_mortality_rate_per_1000
4,Bihar,33.76,23.00
15,Jharkhand,28.81,29.00
23,Meghalaya,27.79,34.00
34,Uttar Pradesh,22.93,37.00
20,Madhya Pradesh,20.63,37.00
3,Assam,19.35,30.00
6,Chhattisgarh,16.37,37.00
26,Odisha,15.68,30.00
25,Nagaland,15.43,10.00
29,Rajasthan,15.31,29.00

In [121]:
df[[
    "state",
    "infant_mortality_rate_per_1000",
    "natural_population_growth_rate"
]].sort_values(
    "natural_population_growth_rate",
    ascending=True
).head(5)

,state,infant_mortality_rate_per_1000,natural_population_growth_rate
0,Andaman and Nicobar Islands,9.00,3.80
10,Goa,6.00,3.90
31,Tamil Nadu,12.00,5.00
17,Kerala,5.00,5.00
27,Puducherry,7.00,5.70

## 12. Mini investigation

Choose one question:

1. Which places combine high poverty and high infant mortality?
2. Which places have high life expectancy despite relatively high poverty?
3. Where is the gap between rural and urban unemployment largest?
4. Which places have both high fertility and high birth rates?
5. Which state or Union Territory looks like an outlier?

Use selection, filtering, sorting and summary statistics.

In [122]:
df.query("multidimensional_poverty_headcount_percent > 20")

,state,gross_enrolment_ratio_secondary_total,birth_rate_per_1000,death_rate_per_1000,infant_mortality_rate_per_1000,maternal_mortality_ratio_per_100000_live_births,total_fertility_rate,life_expectancy_years_total,rural_unemployment_rate_per_1000,urban_unemployment_rate_per_1000,multidimensional_poverty_headcount_percent,natural_population_growth_rate,gender_parity_index_secondary
4,Bihar,44.70,25.80,6.10,23.00,104.00,2.80,69.30,26,73,33.76,19.70,1.10
15,Jharkhand,60.60,20.60,6.30,29.00,54.00,2.10,69.50,5,58,28.81,14.30,1.10
20,Madhya Pradesh,56.70,22.50,6.80,37.00,142.00,2.40,67.60,5,28,20.63,15.80,1.00
23,Meghalaya,62.50,22.70,5.50,34.00,NaN,NaN,NaN,51,140,27.79,17.30,1.40
34,Uttar Pradesh,60.90,23.60,6.50,37.00,141.00,2.60,68.00,22,67,22.93,17.10,1.00

In [124]:
df.query("infant_mortality_rate_per_1000 > 25")

,state,gross_enrolment_ratio_secondary_total,birth_rate_per_1000,death_rate_per_1000,infant_mortality_rate_per_1000,maternal_mortality_ratio_per_100000_live_births,total_fertility_rate,life_expectancy_years_total,rural_unemployment_rate_per_1000,urban_unemployment_rate_per_1000,multidimensional_poverty_headcount_percent,natural_population_growth_rate,gender_parity_index_secondary
3,Assam,61.50,19.80,6.20,30.00,110.00,2.00,68.60,35,74,19.35,13.60,1.20
6,Chhattisgarh,65.60,22.30,8.30,37.00,146.00,2.20,64.60,15,76,16.37,14.00,1.20
12,Haryana,81.00,18.70,6.80,26.00,89.00,1.90,68.80,31,40,7.07,11.90,1.00
15,Jharkhand,60.60,20.60,6.30,29.00,54.00,2.10,69.50,5,58,28.81,14.30,1.10
20,Madhya Pradesh,56.70,22.50,6.80,37.00,142.00,2.40,67.60,5,28,20.63,15.80,1.00
23,Meghalaya,62.50,22.70,5.50,34.00,NaN,NaN,NaN,51,140,27.79,17.30,1.40
26,Odisha,72.30,16.00,7.70,30.00,153.00,1.70,70.50,26,68,15.68,8.40,1.10
29,Rajasthan,74.20,22.90,5.90,29.00,86.00,2.30,70.40,32,77,15.31,16.90,1.00
34,Uttar Pradesh,60.90,23.60,6.50,37.00,141.00,2.60,68.00,22,67,22.93,17.10,1.00

In [125]:
#Madhya Pradesh, Meghalaya, Uttar Pradesh combine high poverty and high infant mortality

## 13. Important limitation

The columns do **not all refer to exactly the same year**. Some indicators are annual, while others use multi-year reference periods.

Before publishing any comparison, check the `Reference Periods` sheet and the original RBI notes.

## 14. Optional: Save the combined sheet as a CSV

In [126]:
# df.to_csv("india_social_demographic_indicators.csv", index=False)

## Weekend practice

Rerun the notebook and change at least three things:

- a state name
- a threshold
- a column used for sorting
- the number inside `head()`
- the variable used to calculate a mean or median
- OR, pick any variable/metric of your liking

Write down one interesting result, one error you encountered, and how you fixed it. Save the notebook as: name_session2. Send it to me by 5 p.m. Sunday. You can email me at: areena.arora@columbia.edu.